name: dumka
description: 'the Dumka Project'

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # UI
  custom_switch_button: ^0.5.0
  material_design_icons_flutter: ^4.0.5755

  google_fonts: ^1.1.1
  flutter_svg: ^0.19.1
  md2_tab_indicator: ^1.0.2

  firebase_core: "0.7.0"
  firebase_analytics: "^7.0.1"
  firebase_crashlytics: "^0.4.0"

  dio: ^3.0.10
  flutter_bloc: ^6.1.1
  shared_preferences: ^0.5.12+4

dev_dependencies:
  flutter_test:
    sdk: flutter


  lint: ^1.2.0




flutter:
  uses-material-design: true

  assets:
    - assets/
    - google_fonts/